### ISSUE TITLE
Improving the documentation website

### ISSUE THREAD

**Issue by pr-Mais** [fluttercommunity/plus_plugins#113]
This issue will be tracking the progress in improving the documentation website [plus.fluttercommunity.dev](https://plus.fluttercommunity.dev).

### TODO list

- [x] Add getting started section with overview of Plus plugins
- [x] Battery➕ docs
- [x] Connectivity➕ docs
- [x] Device Info➕ docs
- [x] Network Info➕ docs
- [x] Package Info➕ docs
- [x] Sensor➕ docs
- [x] Share➕ docs
- [x] Android Alarm Manager➕ docs
- [x] Android Intent➕ docs

**Comment by mhadaily** [comment]
All docs are up now https://plus.fluttercommunity.dev/docs/overview
