### ISSUE TITLE
Plus Plugins Roadmap

### ISSUE THREAD

**Issue by mhadaily** [fluttercommunity/plus_plugins#12]
Hey all 👋

Today I’m excited to announce the upcoming changes and roadmap for the Plus plugins.

The overall mission of PlusPlugins is to provide high-quality plugins for developers to allow them to build Flutter apps. As Flutter grows, we want to ensure that the PlusPlugins plugins grow with it. We support Federated Plugins and have already implemented most of the platforms  and will continue adding the remaining platforms by mid-February 2021

We’ve recently started a triage of FlutterPlugin repository issues to understand the repository's current state and move all of the issues over to this repository and fix them all as soon as possible. 

Our top priorities are introducing a dedicated documentation website, reviewing each plugin in importance order (based on usage & current state), and tackling critical issues.

As we review each plugin by group, we’ll be focusing efforts on the following areas:

Testing: covering the public API (as much as possible) with the dedicated unit and integration tests is essential. We can be confident in adding new features, squashing bugs, and opening up the repository to more external contributors.

Documentation: although the reference API is a great place to understand the plugins, the goal is to write more examples and clear snippets that can be copied and pasted easily. 

We want to ensure that all plugins are interoperable as we work through them, allowing developers to see the benefits from the on-going work as soon as they are available. Therefore we’ll be doing some immediate changes across the board, which will allow the newly updated plugins to be “backward compatible” with plugins that have not yet been updated as part of this process.

**As of December 14, 2020:**
We have come to a pretty stable version so far. We have updated all of our packages with several great commits. All packages are now pretty stable. There are several branches already that team is working on to have remaining Windows and macOS. platforms. Here is our plan: 

- [x] Sending PRs to FlutterEnginee to support missing functionalities that we need for different packages by Dec 1, 2020
- [x] Move all issues from original repo to plus plugins repo to address accordingly  by January 20, 2020
- [x] Finalize PRs and WIP branches for Windows  by January 30, 2020
- [x] Finalize PRs and WIP branches for macOS  by January 30, 2020 
- [x] Improve CD/CI and add additional checks for quality by January 30, 2020
- [x] Introduce NetworkInfoPlus Plugins by February 15, 2021
- [x] Migrate to fully support null-safety by February 15, 2021
- [x] Documentation website by February 15, 2021 
- [x] Update all examples February 15, 2021 
- [x] Release all packages with new major version February 20, 2021 
- [x] Setup Codecoverage February 20, 2021 
- [x] Finalize all-new integration and unit tests February 20, 2021 
- [x] Score 110 for all plugins February 20, 2021 

If you'd like to contribute and help us to deliver the top-notch plugins, feel free to reach out. 

We’ll be updating this issue as we progress through the upgrade to the plugins, so please check back regularly.
The following GitHub users will primarily be focusing on this work going forwards:

@mhadaily 
@jpnurmi 
@miquelbeltran 
@slightfoot
@Nash0x7E2 

If you have any urgent issues / pull requests that you feel you would like us to look at sooner - feel free to tag us, and we'll try our best to look at them as soon as possible.

**Comment by miquelbeltran** [comment]
Started working on "Improve CD/CI and add additional checks for quality" in https://github.com/fluttercommunity/plus_plugins/issues/74

**Comment by Sunbreak** [comment]
Could we open up the Github Discussion? Or is there any place we can discuss with each other besides issues?

**Comment by mhadaily** [comment]
@Sunbreak sounds like a good idea; I opened it experimentally.

**Comment by miquelbeltran** [comment]
I would probably tick "Improve CD/CI and add additional checks for quality" now that @jpnurmi setup integration tests on GH actions too.

**Comment by mhadaily** [comment]
No that we have successfully delivered all milestones, I am going to close this issue. we will re-open a new issue if there will be new roadmap.
