### ISSUE TITLE
e: C:/Users/user/Desktop/Projects/b2c/build/share_plus/.transforms/b739b8a9105a6ee9b581db14ac99efe3/transformed/out/jars/classes.jar!/META-INF/share_plus_release.kotlin_module: Module was compiled with an incompatible version of Kotlin. The binary version of its metadata is 1.9.0, expected version is 1.6.0.[Compile]: 

### ISSUE THREAD

**Issue by coderodilov** [fluttercommunity/plus_plugins#3107]
### Operating System

Win 11

### Plugin

share_plus

### Version

9.0.0

### Flutter SDK

3.22

### Compilation command

e: C:/Users/user/Desktop/Projects/b2c/build/share_plus/.transforms/b739b8a9105a6ee9b581db14ac99efe3/transformed/out/jars/classes.jar!/META-INF/share_plus_release.kotlin_module: Module was compiled with an incompatible version of Kotlin. The binary version of its metadata is 1.9.0, expected version is 1.6.0.

### Dart Dependencies

```yaml
e: C:/Users/user/Desktop/Projects/b2c/build/share_plus/.transforms/b739b8a9105a6ee9b581db14ac99efe3/transformed/out/jars/classes.jar!/META-INF/share_plus_release.kotlin_module: Module was compiled with an incompatible version of Kotlin. The binary version of its metadata is 1.9.0, expected version is 1.6.0.
```

### Native dependencies

```text
e: C:/Users/user/Desktop/Projects/b2c/build/share_plus/.transforms/b739b8a9105a6ee9b581db14ac99efe3/transformed/out/jars/classes.jar!/META-INF/share_plus_release.kotlin_module: Module was compiled with an incompatible version of Kotlin. The binary version of its metadata is 1.9.0, expected version is 1.6.0.
```

### Compilation Error

```shell
e: C:/Users/user/Desktop/Projects/b2c/build/share_plus/.transforms/b739b8a9105a6ee9b581db14ac99efe3/transformed/out/jars/classes.jar!/META-INF/share_plus_release.kotlin_module: Module was compiled with an incompatible version of Kotlin. The binary version of its metadata is 1.9.0, expected version is 1.6.0.
```

### Flutter Doctor

```shell
PS C:\Users\user\Desktop\Projects\b2c\android> flutter doctor -v
[√] Flutter (Channel stable, 3.22.3, on Microsoft Windows [Version 10.0.19045.4651], locale en-US)
    • Flutter version 3.22.3 on channel stable at C:\sdk\flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision b0850beeb2 (8 days ago), 2024-07-16 21:43:41 -0700
    • Engine revision 235db911ba
    • Dart version 3.4.4
    • DevTools version 2.34.3

[√] Windows Version (Installed version of Windows is version 10 or higher)

[√] Android toolchain - develop for Android devices (Android SDK version 34.0.0)
    • Android SDK at C:\Users\user\AppData\Local\Android\sdk
    • Platform android-VanillaIceCream, build-tools 34.0.0
    • Java binary at: C:\Program Files\Android\Android Studio\jbr\bin\java
    • Java version OpenJDK Runtime Environment (build 17.0.10+0--11609105)
    • All Android licenses accepted.

[√] Chrome - develop for the web
    • Chrome at C:\Program Files\Google\Chrome\Application\chrome.exe

[!] Visual Studio - develop Windows apps (Visual Studio Community 2022 17.9.6)
    • Visual Studio at C:\Program Files\Microsoft Visual Studio\2022\Community
    • Visual Studio Community 2022 version 17.9.34728.123
    X Visual Studio is missing necessary components. Please re-run the Visual Studio installer for the "Desktop development with C++" workload, and include these components:
        MSVC v142 - VS 2019 C++ x64/x86 build tools
         - If there are multiple build tool versions available, install the latest
        C++ CMake tools for Windows
        Windows 10 SDK

[√] Android Studio (version 2024.1)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin can be installed from:
       https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
       https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 17.0.10+0--11609105)

[√] Connected device (5 available)
    • SM N976N (mobile)            • R3CMA0E9K4V   • android-arm64  • Android 12 (API 31)
    • sdk gphone64 x86 64 (mobile) • emulator-5554 • android-x64    • Android 12 (API 31) (emulator)
    • Windows (desktop)            • windows       • windows-x64    • Microsoft Windows [Version 10.0.19045.4651]
    • Chrome (web)                 • chrome        • web-javascript • Google Chrome 127.0.6533.72
    • Edge (web)                   • edge          • web-javascript • Microsoft Edge 126.0.2592.113

[√] Network resources
    • All expected network resources are available.
```

### Checklist before submitting a bug

- [X] I searched issues in this repository and couldn't find such bug/problem
- [X] I Google'd a solution and I couldn't find it
- [X] I searched on StackOverflow for a solution and I couldn't find it
- [X] I read the README.md file of the plugin
- [X] I'm using the latest version of the plugin
- [X] All dependencies are up to date with `flutter pub upgrade`
- [X] I did a `flutter clean`
- [X] I tried running the example project
