### ISSUE TITLE
[android_intent_plus] issues from Flutter repository

### ISSUE THREAD

**Issue by mhadaily** [fluttercommunity/plus_plugins#75]
**Todo**

- [x] https://github.com/flutter/flutter/issues/71518 solved by us
- [x] https://github.com/flutter/flutter/issues/65533 solved by us
- [x] ~~https://github.com/flutter/flutter/issues/57431~~ missing info
- [ ] https://github.com/flutter/flutter/issues/54362
- [x] ~~https://github.com/flutter/flutter/issues/52531~~ already solved
- [x] ~~https://github.com/flutter/flutter/issues/45185~~ unrelated
- [x] ~~https://github.com/flutter/flutter/issues/43194~~ already solved in another package
- [x] ~~https://github.com/flutter/flutter/issues/38701~~ already solved
- [x] ~~https://github.com/flutter/flutter/issues/34296~~ cannot be solved

[Check all issues for this plugin](https://github.com/flutter/flutter/issues?q=is%3Aopen+is%3Aissue+label%3A%22p%3A+android_intent%22)

**Comment by miquelbeltran** [comment]
Looking into flutter/flutter#71518

**Comment by miquelbeltran** [comment]
Looking into flutter/flutter#65533

**Comment by miquelbeltran** [comment]
- https://github.com/flutter/flutter/issues/57431 is missing information (no example data)
- flutter/flutter#54362 could be solved by us
- https://github.com/flutter/flutter/issues/52531 seems already resolved
- flutter/flutter#45185 seems unrelated
- flutter/flutter#43194 solved in another package
- flutter/flutter#38701 already supported
- https://github.com/flutter/flutter/issues/34296 doesn't seem valid

So from the rest of the list, only flutter/flutter#54362  seems solvable

**Comment by Elias8** [comment]
The problem with [Intent Plugin: Type Mismatch between Dart's List<String> vs Java String[] flutter/flutter#54362](https://github.com/flutter/flutter/issues/54362) is we are using the `bundle.putStringArrayList` method instead of `bundle.putStringArray` to pass the email addresses or other array arguments.

So since both methods may have different use cases, I am thinking to introduce a new field in the [AndroidIntent](https://github.com/fluttercommunity/plus_plugins/blob/16867ac537dd66cde70a78c07235b899bb5cd2b1/packages/android_intent_plus/lib/android_intent.dart#L18) class called `arrayArguments` or something like that in addition to the current [arguments](https://github.com/fluttercommunity/plus_plugins/blob/16867ac537dd66cde70a78c07235b899bb5cd2b1/packages/android_intent_plus/lib/android_intent.dart#L91) field we have, so that we can pass array arguments to be put into the bundle using the `bundle.putStringArray` method.

What do you think @miquelbeltran @mhadaily?

**Comment by mhadaily** [comment]
it seems a good solution, what do you think @miquelbeltran

**Comment by vbuberen** [comment]
Yay, all issues from the original Flutter repository are fixed. Awesome!
