### ISSUE TITLE
[android_alarm_manager_plus] issues from Flutter repository

### ISSUE THREAD

**Issue by mhadaily** [fluttercommunity/plus_plugins#77]
**Todo**

- [ ] https://github.com/flutter/flutter/issues/70942
- [ ] https://github.com/flutter/flutter/issues/69721
- [ ] https://github.com/flutter/flutter/issues/61854
- [ ] https://github.com/flutter/flutter/issues/58263
- [ ] https://github.com/flutter/flutter/issues/54533
- [ ] https://github.com/flutter/flutter/issues/52528
- [ ] https://github.com/flutter/flutter/issues/51413
- [ ] https://github.com/flutter/flutter/issues/50826
- [ ] https://github.com/flutter/flutter/issues/49955
- [ ] https://github.com/flutter/flutter/issues/48751
- [ ] https://github.com/flutter/flutter/issues/48440
- [ ] https://github.com/flutter/flutter/issues/48151
- [ ] https://github.com/flutter/flutter/issues/42907
- [ ] https://github.com/flutter/flutter/issues/41608
- [ ] https://github.com/flutter/flutter/issues/40030
- [ ] https://github.com/flutter/flutter/issues/39314
- [ ] https://github.com/flutter/flutter/issues/39241
- [ ] https://github.com/flutter/flutter/issues/34254
- [ ] https://github.com/flutter/flutter/issues/32516
- [ ] https://github.com/flutter/flutter/issues/30918
- [ ] https://github.com/flutter/flutter/issues/30555
- [ ] https://github.com/flutter/flutter/issues/28600
- [ ] https://github.com/flutter/flutter/issues/26995
- [ ] https://github.com/flutter/flutter/issues/26897
- [ ] https://github.com/flutter/flutter/issues/26813
- [ ] https://github.com/flutter/flutter/issues/26639
- [ ] https://github.com/flutter/flutter/issues/26582
- [ ] https://github.com/flutter/flutter/issues/26572
- [ ] https://github.com/flutter/flutter/issues/25912
- [x] https://github.com/flutter/flutter/issues/20913

[Link to all ](https://github.com/flutter/flutter/issues?page=2&q=is%3Aopen+is%3Aissue+label%3A%22p%3A+android_alarm_manager%22+sort%3Acreated-desc)
