### ISSUE TITLE
[package_info_plus] issues from Flutter repository

### ISSUE THREAD

**Issue by mhadaily** [fluttercommunity/plus_plugins#78]
**Todo:**

- [ ] https://github.com/flutter/flutter/issues/67739
- [ ] https://github.com/flutter/flutter/issues/59636
- [ ] https://github.com/flutter/flutter/issues/53413
- [ ] https://github.com/flutter/flutter/issues/42510
- [x] https://github.com/flutter/flutter/issues/41729
- [x] https://github.com/flutter/flutter/issues/41728
- [x] https://github.com/flutter/flutter/issues/36709
- [ ] https://github.com/flutter/flutter/issues/11482

[Link to all issues](https://github.com/flutter/flutter/issues?q=is%3Aopen+is%3Aissue+sort%3Acreated-desc+label%3A%22p%3A+package_info%22+)

**Comment by ekuleshov** [comment]
Any chance support for retrieving app store info could be added?
For some details see https://github.com/flutter/flutter/issues/67739

**Comment by mhadaily** [comment]
It's possible for sure. We can discuss this in our next meeting. will keep you posted

**Comment by fabiancrx** [comment]
@mhadaily it seems all issues are closed. Maybe this umbrella issue might be closed too?

> **Todo:**
> 
> * [ ]  [extend package_info plugin to return installer info flutter/flutter#67739](https://github.com/flutter/flutter/issues/67739)
> * [ ]  [[package_info]  buildNumber inconsistent on Honor devices  flutter/flutter#59636](https://github.com/flutter/flutter/issues/59636)
> * [ ]  [package_info readme file is wrong: dependency constraint single quote flutter/flutter#53413](https://github.com/flutter/flutter/issues/53413)
> * [ ]  [package_info.appName is null on iOS flutter/flutter#42510](https://github.com/flutter/flutter/issues/42510)
> * [x]  [[package_info] Implement Linux support flutter/flutter#41729](https://github.com/flutter/flutter/issues/41729)
> * [x]  [[package_info] Implement Windows support flutter/flutter#41728](https://github.com/flutter/flutter/issues/41728)
> * [x]  [Get flutter version from package_info flutter/flutter#36709](https://github.com/flutter/flutter/issues/36709)
> * [ ]  [Crashy example should show how to use package_info to include release information flutter/flutter#11482](https://github.com/flutter/flutter/issues/11482)
> 
> [Link to all issues](https://github.com/flutter/flutter/issues?q=is%3Aopen+is%3Aissue+sort%3Acreated-desc+label%3A%22p%3A+package_info%22+)

**Comment by ekuleshov** [comment]
> @mhadaily it seems all issues are closed. Maybe this umbrella issue might be closed too?

Am I reading it wrong that only 3 out of 7 issues are closed? And not all have mirroring issues in this repo.

**Comment by mhadaily** [comment]
@fabiancrx thanks for noticing, we will leave this still open for our reference. 

@ekuleshov most of these issues are not relevant anymore however, we still want to keep an eye on them.
