### ISSUE TITLE
[device_info_plus] issues from Flutter repository

### ISSUE THREAD

**Issue by mhadaily** [fluttercommunity/plus_plugins#79]
**Todo**

- [ ] https://github.com/flutter/flutter/issues/68181
- [ ] https://github.com/flutter/flutter/issues/64569
- [ ] https://github.com/flutter/flutter/issues/63324
- [ ] https://github.com/flutter/flutter/issues/57571
- [ ] https://github.com/flutter/flutter/issues/54430
- [ ] https://github.com/flutter/flutter/issues/54347
- [ ] https://github.com/flutter/flutter/issues/50123
- [ ] https://github.com/flutter/flutter/issues/49296
- [ ] https://github.com/flutter/flutter/issues/41782
- [ ] https://github.com/flutter/flutter/issues/41099
- [x] https://github.com/flutter/flutter/issues/39674
- [ ] https://github.com/flutter/flutter/issues/29042

[Link to all issues](https://github.com/flutter/flutter/issues?q=is%3Aopen+is%3Aissue+sort%3Acreated-desc+label%3A%22p%3A+device_info%22+)
