### ISSUE TITLE
[sensors_plus] issues from Flutter repository

### ISSUE THREAD

**Issue by mhadaily** [fluttercommunity/plus_plugins#80]
**Todo**

- [ ] https://github.com/flutter/flutter/issues/65620
- [ ] https://github.com/flutter/flutter/issues/56997
- [ ] https://github.com/flutter/flutter/issues/49608
- [ ] https://github.com/flutter/flutter/issues/47703
- [ ] https://github.com/flutter/flutter/issues/43653
- [ ] https://github.com/flutter/flutter/issues/26078
- [ ] https://github.com/flutter/flutter/issues/25971
- [ ] https://github.com/flutter/flutter/issues/19386

[Link to all issues ](https://github.com/flutter/flutter/issues?q=is%3Aopen+is%3Aissue+sort%3Acreated-desc+label%3A%22p%3A+sensors%22+)

**Comment by thertzelle** [comment]
I'm sorry if my message was intentionally deleted. I was wondering if these issues (specifically https://github.com/flutter/flutter/issues/25971) was on your immediate todo list? I have a use case that needs to define the sample rate and I'm willing to investigate it if its something that you will not be doing anytime soon. Please let me know. Thank you.

**Comment by mhadaily** [comment]
Hello 
This is on our list and we may pick that anytime. If you'd like to help and investigate to address these issues, you are more than welcome.

**Comment by xnio94** [comment]
any updates on the sampling rate

**Comment by Ortes** [comment]
[Here](https://github.com/fluttercommunity/plus_plugins/pull/2506) is a PR for [Consider adding timestamps to sensor events flutter/flutter#26078](https://github.com/flutter/flutter/issues/26078)
