### ISSUE TITLE
[share_plus] issues from Flutter repository

### ISSUE THREAD

**Issue by mhadaily** [fluttercommunity/plus_plugins#82]
**Todo**

- [ ] https://github.com/flutter/flutter/issues/70488
- [ ] https://github.com/flutter/flutter/issues/70315
- [ ] https://github.com/flutter/flutter/issues/69201
- [ ] https://github.com/flutter/flutter/issues/67637
- [ ] https://github.com/flutter/flutter/issues/67103
- [ ] https://github.com/flutter/flutter/issues/66969
- [ ] https://github.com/flutter/flutter/issues/66513
- [ ] https://github.com/flutter/flutter/issues/62548
- [x] https://github.com/flutter/flutter/issues/55330
- [ ] https://github.com/flutter/flutter/issues/55061
- [ ] https://github.com/flutter/flutter/issues/54244
- [ ] https://github.com/flutter/flutter/issues/53131
- [ ] https://github.com/flutter/flutter/issues/44293
- [ ] https://github.com/flutter/flutter/issues/36438
- [ ] https://github.com/flutter/flutter/issues/11886
- [x] https://github.com/flutter/flutter/issues/9817

[Link to all issues ](https://github.com/flutter/flutter/issues?q=is%3Aopen+is%3Aissue+sort%3Acreated-desc+label%3A%22p%3A+share%22+)
