### ISSUE TITLE
[connectivity_plus] issues from Flutter repository

### ISSUE THREAD

**Issue by mhadaily** [fluttercommunity/plus_plugins#83]
**Todo**

- [ ] https://github.com/flutter/flutter/issues/69159
- [ ] https://github.com/flutter/flutter/issues/64454
- [ ] https://github.com/flutter/flutter/issues/59417
- [ ] https://github.com/flutter/flutter/issues/54460
- [ ] https://github.com/flutter/flutter/issues/51529
- [ ] https://github.com/flutter/flutter/issues/49291
- [ ] https://github.com/flutter/flutter/issues/44580
- [ ] https://github.com/flutter/flutter/issues/43488
- [x] https://github.com/flutter/flutter/issues/41713
- [x] https://github.com/flutter/flutter/issues/41712
- [ ] https://github.com/flutter/flutter/issues/39842
- [ ] https://github.com/flutter/flutter/issues/37618
- [ ] https://github.com/flutter/flutter/issues/35802
- [ ] https://github.com/flutter/flutter/issues/30952
- [ ] https://github.com/flutter/flutter/issues/20980
- [ ] https://github.com/flutter/flutter/issues/12446

[Link to all issues ](https://github.com/flutter/flutter/issues?q=is%3Aopen+is%3Aissue+sort%3Acreated-desc+label%3A%22p%3A+connectivity%22+)

**Comment by epulsecart** [comment]
Thank you very much sir! that is helpful

**Comment by Sameerkash** [comment]
@mhadaily  what channel should I be on? Getting version solving failed while doing  `packages get` 

also isn't there any script for pulling dependencies? Like `updating-packages`?

**Comment by mhadaily** [comment]
have you followed this https://github.com/fluttercommunity/plus_plugins/blob/main/CONTRIBUTING.md? 

we use Melos and you can simply use that to scaffold your local repo. 

We use `dev channel` @jpnurmi or @miquelbeltran  can correct me here.

**Comment by Sameerkash** [comment]
@mhadaily , sorry about that, got melos, hadn't seen bootstrap. Bootstrapped now 👍🏻. 
and using the dev channel. 

Thanks

**Comment by miquelbeltran** [comment]
Nope, we use stable, but will be switching to beta for the null safety migration.

**Comment by Sameerkash** [comment]
Oh cool!, I'm back on beta, had problems with dev.
